name: YARA Scan

on:
  repository_dispatch:
    types: [yara]

permissions:
  contents: write
  issues: write
  security-events: write

jobs:
  yara-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install YARA
      run: |
        sudo apt-get update
        sudo apt-get install -y yara

    - name: Clone YARA rules
      run: |
        git clone https://github.com/Yara-Rules/rules.git yara-rules

    - name: Compile YARA rules
      run: |
        find yara-rules/ -name '*.yar' > rule_files.txt
        xargs -a rule_files.txt yarac - compiled_rules.yar
    
    - name: Run YARA scan
      run: |
        yara -C compiled_rules.yar ./ > yara_scan_results.txt

    - name: Upload YARA scan results
      uses: actions/upload-artifact@v4
      with:
        name: yara-scan-results
        path: yara_scan_results.txt
        include-hidden-files: true
